// file: CoolerMappingConfigBean.proto
package Flydigi.SharedResources.data.protobuf;
import "CoolerEnum.proto";
import "Common.proto";

message CoolerMappingConfigBean {
  int32 cfg_id = 1;
  string title = 2;
  FanConfigProto fan_config = 3;
  RgbConfig rgb_config = 4;
  SystemConfig system_config = 5;
}

message CoolerMappingConfigBeans {
  repeated CoolerMappingConfigBean config_items = 1;
}

message FanConfigProto {
  FanModeProto mode = 1;
  FanModeProto last_mode = 2;
  uint32 speed = 3;
  uint32 min_speed = 4;
  uint32 max_speed = 5;
  uint32 gear1_speed = 6;
  uint32 gear2_speed = 7;
  uint32 gear3_speed = 8;
  uint32 gear4_speed = 9;
  FanAccLevelProto acc_level = 10;
}

message RgbConfig {
  RgbEffectTypeProto current_effect_type = 1;
  repeated EffectConfigsEntry effect_configs = 2;
  uint32 led_count = 3;
  RgbEffectTypeProto current_smart_effect_type = 4;
  RgbEffectTypeProto last_effect_type = 5;
  message EffectConfigsEntry {
    string key = 1;
    RgbEffectConfig value = 2;
  }
}

message RgbEffectConfig {
  repeated Color colors = 1;
  uint32 brightness = 2;
  uint32 speed = 3;
  uint32 led_count = 4;
  repeated uint32 led_indices = 5;
  string effect_name = 6;
  repeated CustomParamsEntry custom_params = 7;
  message CustomParamsEntry {
    string key = 1;
    string value = 2;
  }
}

message SystemConfig {
  uint32 acc_level = 1;
  bool power_auto_start = 2;
  IntelligentStartStopModeProto intelligent_start_stop = 3;
  bool gear_light = 4;
  IntelligentCoolingConfig cooling_config = 5;
  VbusStatusProto vbus_mode = 6;
}

message IntelligentCoolingConfig {
  IntelligentCoolingPresetProto current_mode = 1;
  CustomCurveConfig custom_curve = 2;
  bool enable_hysteresis = 3;
  float hysteresis_delta = 4;
}

message CustomCurveConfig {
  repeated SpeedCurvePoint points = 1;
  string last_modified = 2;
}

message SpeedCurvePoint {
  float temperature = 1;
  uint32 speed = 2;
}

message CoolerStatusReport {
  string device_id = 1;
  bool is_shutdown = 2;
  RunModeProto device_mode = 3;
  bool is_test_mode = 4;
  uint32 real_speed = 5;
  uint32 aim_speed = 6;
  uint32 temperature = 7;
  uint32 voltage = 8;
  CoolerStatusProto status = 9;
}

message CoolerFanConfig {
  FanModeProto mode = 1;
  uint32 target_speed = 2;
  uint32 current_speed = 3;
  uint32 min_speed = 4;
  uint32 max_speed = 5;
  bool smart_mode_enabled = 6;
}

message CoolerRgbEffectConfig {
  RgbEffectTypeProto effect_type = 1;
  Color primary_color = 2;
  Color secondary_color = 3;
  RgbSpeedProto speed = 4;
  RgbBrightnessProto brightness = 5;
  bool enabled = 6;
}

message CoolerGearLightConfig {
  bool enabled = 1;
  Color color = 2;
  uint32 brightness = 3;
}

message CoolerAdvancedConfig {
  bool auto_start = 1;
  IntelligentStartStopModeProto intelligent_start_stop = 2;
  RunModeProto default_run_mode = 3;
  OverclockTypeProto overclock_type = 4;
  uint32 temperature_threshold = 5;
  bool temperature_protection = 6;
}

