// file: KeyboardEnum.proto
package Flydigi.SharedResources.data.protobuf;

enum KeyboardKey {
  Keyboard_None = 0;
  Keyboard_A = 65;
  Keyboard_Add = 107;
  Keyboard_Alt = 262144;
  Keyboard_Apps = 93;
  Keyboard_Attn = 246;
  Keyboard_B = 66;
  Keyboard_Back = 8;
  Keyboard_BrowserBack = 166;
  Keyboard_BrowserFavorites = 171;
  Keyboard_BrowserForward = 167;
  Keyboard_BrowserHome = 172;
  Keyboard_BrowserRefresh = 168;
  Keyboard_BrowserSearch = 170;
  Keyboard_BrowserStop = 169;
  Keyboard_C = 67;
  Keyboard_Cancel = 3;
  Keyboard_Capital = 20;
  Keyboard_Clear = 12;
  Keyboard_Control = 131072;
  Keyboard_ControlKey = 17;
  Keyboard_Crsel = 247;
  Keyboard_D = 68;
  Keyboard_D0 = 48;
  Keyboard_D1 = 49;
  Keyboard_D2 = 50;
  Keyboard_D3 = 51;
  Keyboard_D4 = 52;
  Keyboard_D5 = 53;
  Keyboard_D6 = 54;
  Keyboard_D7 = 55;
  Keyboard_D8 = 56;
  Keyboard_D9 = 57;
  Keyboard_Decimal = 110;
  Keyboard_Delete = 46;
  Keyboard_Divide = 111;
  Keyboard_Down = 40;
  Keyboard_E = 69;
  Keyboard_End = 35;
  Keyboard_Enter = 13;
  Keyboard_EraseEof = 249;
  Keyboard_Escape = 27;
  Keyboard_Execute = 43;
  Keyboard_Exsel = 248;
  Keyboard_F = 70;
  Keyboard_F1 = 112;
  Keyboard_F10 = 121;
  Keyboard_F11 = 122;
  Keyboard_F12 = 123;
  Keyboard_F13 = 124;
  Keyboard_F14 = 125;
  Keyboard_F15 = 126;
  Keyboard_F16 = 127;
  Keyboard_F17 = 128;
  Keyboard_F18 = 129;
  Keyboard_F19 = 130;
  Keyboard_F2 = 113;
  Keyboard_F20 = 131;
  Keyboard_F21 = 132;
  Keyboard_F22 = 133;
  Keyboard_F23 = 134;
  Keyboard_F24 = 135;
  Keyboard_F3 = 114;
  Keyboard_F4 = 115;
  Keyboard_F5 = 116;
  Keyboard_F6 = 117;
  Keyboard_F7 = 118;
  Keyboard_F8 = 119;
  Keyboard_F9 = 120;
  Keyboard_FinalMode = 24;
  Keyboard_G = 71;
  Keyboard_H = 72;
  Keyboard_HangulMode = 21;
  Keyboard_HanjaMode = 25;
  Keyboard_Help = 47;
  Keyboard_Home = 36;
  Keyboard_I = 73;
  Keyboard_IMEAccept = 30;
  Keyboard_IMEConvert = 28;
  Keyboard_IMEModeChange = 31;
  Keyboard_IMENonConvert = 29;
  Keyboard_Insert = 45;
  Keyboard_J = 74;
  Keyboard_JunjaMode = 23;
  Keyboard_K = 75;
  Keyboard_KeyCode = 65535;
  Keyboard_L = 76;
  Keyboard_LaunchApplication1 = 182;
  Keyboard_LaunchApplication2 = 183;
  Keyboard_LaunchMail = 180;
  Keyboard_LButton = 1;
  Keyboard_LControlKey = 162;
  Keyboard_Left = 37;
  Keyboard_LineFeed = 10;
  Keyboard_LMenu = 164;
  Keyboard_LShiftKey = 160;
  Keyboard_LWin = 91;
  Keyboard_M = 77;
  Keyboard_MButton = 4;
  Keyboard_MediaNextTrack = 176;
  Keyboard_MediaPlayPause = 179;
  Keyboard_MediaPreviousTrack = 177;
  Keyboard_MediaStop = 178;
  Keyboard_Menu = 18;
  Keyboard_Modifiers = 18446744073709486080;
  Keyboard_Multiply = 106;
  Keyboard_N = 78;
  Keyboard_NoName = 252;
  Keyboard_NumLock = 144;
  Keyboard_NumPad0 = 96;
  Keyboard_NumPad1 = 97;
  Keyboard_NumPad2 = 98;
  Keyboard_NumPad3 = 99;
  Keyboard_NumPad4 = 100;
  Keyboard_NumPad5 = 101;
  Keyboard_NumPad6 = 102;
  Keyboard_NumPad7 = 103;
  Keyboard_NumPad8 = 104;
  Keyboard_NumPad9 = 105;
  Keyboard_O = 79;
  Keyboard_Oem8 = 223;
  Keyboard_OemBackslash = 226;
  Keyboard_OemClear = 254;
  Keyboard_OemCloseBrackets = 221;
  Keyboard_OemComma = 188;
  Keyboard_OemMinus = 189;
  Keyboard_OemOpenBrackets = 219;
  Keyboard_OemPeriod = 190;
  Keyboard_OemPipe = 220;
  Keyboard_OemPlus = 187;
  Keyboard_OemQuestion = 191;
  Keyboard_OemQuotes = 222;
  Keyboard_OemSemicolon = 186;
  Keyboard_Oemtilde = 192;
  Keyboard_P = 80;
  Keyboard_Pa1 = 253;
  Keyboard_Packet = 231;
  Keyboard_PageDown = 34;
  Keyboard_PageUp = 33;
  Keyboard_Pause = 19;
  Keyboard_Play = 250;
  Keyboard_Print = 42;
  Keyboard_PrintScreen = 44;
  Keyboard_ProcessKey = 229;
  Keyboard_Q = 81;
  Keyboard_R = 82;
  Keyboard_RButton = 2;
  Keyboard_RControlKey = 163;
  Keyboard_Right = 39;
  Keyboard_RMenu = 165;
  Keyboard_RShiftKey = 161;
  Keyboard_RWin = 92;
  Keyboard_S = 83;
  Keyboard_Scroll = 145;
  Keyboard_Select = 41;
  Keyboard_SelectMedia = 181;
  Keyboard_Separator = 108;
  Keyboard_Shift = 65536;
  Keyboard_ShiftKey = 16;
  Keyboard_Sleep = 95;
  Keyboard_Space = 32;
  Keyboard_Subtract = 109;
  Keyboard_T = 84;
  Keyboard_Tab = 9;
  Keyboard_U = 85;
  Keyboard_Up = 38;
  Keyboard_V = 86;
  Keyboard_VolumeDown = 174;
  Keyboard_VolumeMute = 173;
  Keyboard_VolumeUp = 175;
  Keyboard_W = 87;
  Keyboard_X = 88;
  Keyboard_XButton1 = 5;
  Keyboard_XButton2 = 6;
  Keyboard_Y = 89;
  Keyboard_Z = 90;
  Keyboard_Zoom = 251;
  Keyboard_WheelUp = 433;
  Keyboard_WheelDown = 434;
}

enum KeyID {
  KB_ID_None = 0;
  KB_ID_ErrorRollOver1 = 1;
  KB_ID_POSTFail1 = 2;
  KB_ID_ErrorUndefined1 = 3;
  KB_ID_A = 4;
  KB_ID_B = 5;
  KB_ID_C = 6;
  KB_ID_D = 7;
  KB_ID_E = 8;
  KB_ID_F = 9;
  KB_ID_G = 10;
  KB_ID_H = 11;
  KB_ID_I = 12;
  KB_ID_J = 13;
  KB_ID_K = 14;
  KB_ID_L = 15;
  KB_ID_M = 16;
  KB_ID_N = 17;
  KB_ID_O = 18;
  KB_ID_P = 19;
  KB_ID_Q = 20;
  KB_ID_R = 21;
  KB_ID_S = 22;
  KB_ID_T = 23;
  KB_ID_U = 24;
  KB_ID_V = 25;
  KB_ID_W = 26;
  KB_ID_X = 27;
  KB_ID_Y = 28;
  KB_ID_Z = 29;
  KB_ID_1 = 30;
  KB_ID_2 = 31;
  KB_ID_3 = 32;
  KB_ID_4 = 33;
  KB_ID_5 = 34;
  KB_ID_6 = 35;
  KB_ID_7 = 36;
  KB_ID_8 = 37;
  KB_ID_9 = 38;
  KB_ID_0 = 39;
  KB_ID_Return = 40;
  KB_ID_Esc = 41;
  KB_ID_Backspace = 42;
  KB_ID_Tab = 43;
  KB_ID_Spacebar = 44;
  KB_ID_Minus = 45;
  KB_ID_Equal = 46;
  KB_ID_LBracket = 47;
  KB_ID_RBracket = 48;
  KB_ID_Backslash = 49;
  KB_ID_Non_US1 = 50;
  KB_ID_Semicolon = 51;
  KB_ID_Quote = 52;
  KB_ID_Grave = 53;
  KB_ID_Comma = 54;
  KB_ID_Period = 55;
  KB_ID_Slash = 56;
  KB_ID_Caps = 57;
  KB_ID_F1 = 58;
  KB_ID_F2 = 59;
  KB_ID_F3 = 60;
  KB_ID_F4 = 61;
  KB_ID_F5 = 62;
  KB_ID_F6 = 63;
  KB_ID_F7 = 64;
  KB_ID_F8 = 65;
  KB_ID_F9 = 66;
  KB_ID_F10 = 67;
  KB_ID_F11 = 68;
  KB_ID_F12 = 69;
  KB_ID_PrintScreen = 70;
  KB_ID_ScrollLock = 71;
  KB_ID_Pause = 72;
  KB_ID_Insert = 73;
  KB_ID_Home = 74;
  KB_ID_PageUp = 75;
  KB_ID_Delete = 76;
  KB_ID_End = 77;
  KB_ID_PageDown = 78;
  KB_ID_RightArrow = 79;
  KB_ID_LeftArrow = 80;
  KB_ID_DownArrow = 81;
  KB_ID_UpArrow = 82;
  KB_ID_KP_Num = 83;
  KB_ID_KP_Divide = 84;
  KB_ID_KP_Multiply = 85;
  KB_ID_KP_Minus = 86;
  KB_ID_KP_Plus = 87;
  KB_ID_KP_ENTER = 88;
  KB_ID_KP_1 = 89;
  KB_ID_KP_2 = 90;
  KB_ID_KP_3 = 91;
  KB_ID_KP_4 = 92;
  KB_ID_KP_5 = 93;
  KB_ID_KP_6 = 94;
  KB_ID_KP_7 = 95;
  KB_ID_KP_8 = 96;
  KB_ID_KP_9 = 97;
  KB_ID_KP_0 = 98;
  KB_ID_KP_Period = 99;
  KB_ID_Non_US2 = 100;
  KB_ID_Application = 101;
  KB_ID_Power = 102;
  KB_ID_LControl = 224;
  KB_ID_LShift = 225;
  KB_ID_LAlt = 226;
  KB_ID_LWin = 227;
  KB_ID_RControl = 228;
  KB_ID_RShift = 229;
  KB_ID_RAlt = 230;
  KB_ID_RWin = 231;
}

